
services:
  jenkins:
    build: ./CI-CD/Jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000" 
    volumes:
      - ./CI-CD/Jenkins/jenkins_home:/var/jenkins_home

